CREATE TABLE IF NOT EXISTS FINGERPRINTS (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  song_fk INTEGER NOT NULL,
  hash VARCHAR(40) NOT NULL,
  offset INTEGER NOT NULL,
  FOREIGN KEY (song_fk) REFERENCES SONGS (song_id)
);
